# Generated by Django 5.2.8 on 2026-01-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_managers_passwordresetotp_delete_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetotp',
            old_name='otp_hash',
            new_name='otp',
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='jti_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='reset_jti',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
