# Generated by Django 5.2.8 on 2026-01-12 20:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0002_alter_business_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('operating', 'Operating Expense'), ('inventory', 'Inventory Purchase')], help_text='Categorize expenses for tax purposes (Operating vs Inventory)', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='InventoryPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_end', models.DateField(help_text='End date of the period (e.g., 2026-12-31)')),
                ('closing_value', models.DecimalField(decimal_places=2, help_text='Total value of unsold stock at the end of this period', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_periods', to='bookkeeping.business')),
            ],
            options={
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['business', 'period_end'], name='bookkeeping_busines_9f5cb6_idx')],
                'unique_together': {('business', 'period_end')},
            },
        ),
    ]
