# Generated by Django 5.2.8 on 2026-01-12 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0003_transaction_expense_type_inventoryperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bookkeeping.business'),
        ),
    ]
