# Generated by Django 5.2.8 on 2025-12-23 09:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('business_type', models.CharField(blank=True, choices=[('', 'Prefer not to say'), ('retail', 'Retail/Shop'), ('services', 'Services'), ('food', 'Food/Restaurant'), ('trade', 'Trading/Import-Export'), ('manufacturing', 'Manufacturing'), ('other', 'Other')], default='', max_length=50)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Waitlist Entry',
                'verbose_name_plural': 'Waitlist Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
